version: '3.8'

services:
  app:
    build: .
    container_name: nextcloud-app
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    restart: always

volumes:
  nextcloud_data:
